export enum SharedResourceType {
    VPC_ID = 'VPC_ID',
    ECS_CLUSTER_NAME = 'ECS_CLUSTER_NAME',
    DATABASE_CLUSTER_IDENTIFIER = 'DATABASE_CLUSTER_IDENTIFIER',
    DATABASE_SECURITY_GROUP_ID = 'DATABASE_SECURITY_GROUP_ID',
    ECR_REPOSITORY_NAME = 'ECR_REPOSITORY_NAME',
    ALB_LOAD_BALANCER_ARN = 'ALB_LOAD_BALANCER_ARN',
    ALB_LOAD_BALANCER_LISTENER_ARN = 'ALB_LOAD_BALANCER_LISTENER_ARN',
    ALB_LOAD_BALANCER_SECURITY_GROUP_ID = 'ALB_LOAD_BALANCER_SECURITY_GROUP_ID',
    ALB_SECRET_HTTP_HEADER_VALUE = 'ALB_SECRET_HTTP_HEADER_VALUE',
    CACHE_CLUSTER_ENDPOINT_ADDRESS = 'CACHE_CLUSTER_ENDPOINT_ADDRESS',
    CACHE_CLUSTER_ENDPOINT_PORT = 'CACHE_CLUSTER_ENDPOINT_PORT',
    CACHE_CLUSTER_SECURITY_GROUP_ID = 'CACHE_CLUSTER_SECURITY_GROUP_ID',
    DATABASE_SECRET_ARN = 'DATABASE_SECRET_ARN',
    DATABASE_MIGRATOR_SECRET_ARN = 'DATABASE_MIGRATOR_SECRET_ARN',
    DATABASE_READ_WRITE_SECRET_ARN = 'DATABASE_READ_WRITE_SECRET_ARN',
    API_TEST_COGNITO_USER_POOL_ARN = 'API_TEST_COGNITO_USER_POOL_ARN',
    ALMA_SSO_MANAGEMENT_API_KEY_SECRET = 'ALMA_SSO_MANAGEMENT_API_KEY_SECRET',
    OAUTH2_ETUOVI_CLIENT_ID = 'OAUTH2_ETUOVI_CLIENT_ID',
    OAUTH2_ETUOVI_CLIENT_SECRET = 'OAUTH2_ETUOVI_CLIENT_SECRET',
    OAUTH2_ETUOVI_API_KEY = 'OAUTH2_ETUOVI_API_KEY',
    ETUOVI_API_BASE_URL = 'ETUOVI_API_BASE_URL',
    ETUOVI_PUBLIC_API_BASE_URL = 'ETUOVI_PUBLIC_API_BASE_URL',
    TEST_DATA_BUCKET_NAME = 'TEST_DATA_BUCKET_NAME',
    STATIC_MEDIA_S3_BUCKET_ARN = 'STATIC_MEDIA_S3_BUCKET_ARN',
    TEMP_UPLOADED_MEDIA_S3_BUCKET_ARN = 'TEMP_UPLOADED_MEDIA_S3_BUCKET_ARN',
    TOP_LEVEL_HOSTED_ZONE_ID = 'TOP_LEVEL_HOSTED_ZONE_ID',
    TOP_LEVEL_HOSTED_ZONE_NAME = 'TOP_LEVEL_HOSTED_ZONE_NAME',
    INTERNAL_SUBDOMAIN_WILDCARD_ACM_CERTIFICATE_ARN = 'INTERNAL_SUBDOMAIN_WILDCARD_ACM_CERTIFICATE_ARN',
    LAMBDA_AUTHORIZER_ARN = 'LAMBDA_AUTHORIZER_ARN',
    ENVIRONMENT_LOGGROUP_ARN = 'ENVIRONMENT_LOGGROUP_ARN',
    TEST_SUPPORT_SG_ID = 'TEST_SUPPORT_SG_ID',
    TEST_SUPPORT_BUCKET_NAME = 'TEST_SUPPORT_BUCKET_NAME',
    CODESTAR_GITHUB_ALMAMEDIA_CONNECTION_ARN = 'CODESTAR_GITHUB_ALMAMEDIA_CONNECTION_ARN',
    AURORA_MIGRATOR_LAMBDA_SG_ID = 'AURORA_MIGRATOR_LAMBDA_SG_ID',
    TEMPLATE_API_ENDPOINT_EXECUTE_URL = 'TEMPLATE_API_ENDPOINT_EXECUTE_URL',
    /**
     * This is needed when generating image proxy urls.
     */
    IMAGE_PROXY_BUCKET_TO_ORIGIN = 'IMAGE_PROXY_BUCKET_TO_ORIGIN',
    /**
     * Cross region resources
     *
     * Note: To keep our utils simple, this is the best solution.
     * Creating a custom class for these has been tried, but it was an
     * unnecessarily complex solution
     *
     * CROSS_REGION/${region_where_resource_is_created}/${identifier_for_parameter}
     */
    GLOBAL_WACL_ARN = 'CROSS_REGION/us-east-1/GLOBAL_WACL_ARN',
    CLOUDFRONT_SUBDOMAIN_WILDCARD_ACM_CERTIFICATE_ARN = 'CROSS_REGION/us-east-1/CLOUDFRONT_SUBDOMAIN_WILDCARD_ACM_CERTIFICATE_ARN',
    CLOUDFRONT_TOP_LEVEL_HOSTED_ZONE_NAME = 'CROSS_REGION/eu-west-1/CLOUDFRONT_TOP_LEVEL_HOSTED_ZONE_NAME',
    CLOUDFRONT_TOP_LEVEL_HOSTED_ZONE_ID = 'CROSS_REGION/eu-west-1/CLOUDFRONT_TOP_LEVEL_HOSTED_ZONE_ID',
}
