export enum SharedResourceType {
    VPC_ID,
    ECS_CLUSTER_NAME,
    DATABASE_CLUSTER_IDENTIFIER,
    ECR_REPOSITORY_NAME,
    ALB_LOAD_BALANCER_ARN,
    ALB_LOAD_BALANCER_LISTENER_ARN,
    ALB_LOAD_BALANCER_SECURITY_GROUP_ID,
    CACHE_CLUSTER_ENDPOINT_ADDRESS,
    CACHE_CLUSTER_ENDPOINT_PORT,
    DATABASE_SECRET_ARN,
}
