name: Destroy environment infra
on:
  delete
jobs:
  delete:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'preview/')
    steps:
      - uses: actions/checkout@v2
      - name: Set account to dev & environment to preview
        if: startsWith(github.event.ref, 'preview/')
        run: |
          echo "ENVIRONMENT=${{ github.event.ref }}" >> $GITHUB_ENV
          echo "ACCOUNT=dev" >> $GITHUB_ENV
      - name: Get access for alma packages
        run: echo "GITHUB_ACCESS_TOKEN=${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}" >> $GITHUB_ENV
      - name: install deps
        working-directory: ./infra
        run: |
          npm install --prefer-online
          npm run build:all
      - name: destroy all stacks
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CDK_USER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_USER_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile deploy_profile
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile deploy_profile
          aws configure set region eu-west-1 --profile deploy_profile
          npx cdk destroy --context account=${{ env.ACCOUNT }} --context environment=${{ env.ENVIRONMENT }} --profile deploy_profile --require-approval never --all --force
