name: Deploy full environment
on:
  create:
    branches:
      - "feature/**"
concurrency:
  group: refs/heads/${{ github.event.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    if: startsWith(github.event.ref, 'feature/')
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: './infra/package-lock.json'
      - name: Notify slack success
        if: success()
        id: slack # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.MEPA_ASUMINEN_OVIPRO_SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel: 'ovi_pro_pipeline_development_deployments'
          status: STARTED
          color: warning
      - name: Set account to dev & environment to feature (from branch)
        if: startsWith(github.event.ref, 'feature/')
        run: |
          echo "ENVIRONMENT=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "ACCOUNT=dev" >> $GITHUB_ENV
      - name: Get access for alma packages
        run: echo "GITHUB_ACCESS_TOKEN=${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}" >> $GITHUB_ENV
      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
                "id": "mepa-ovipro",
                "username": "${{ secrets.MEPA_GH_ACTIONS_BOT_USERNAME }}",
                "password": "${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}"
            }]
      - name: install deps & build
        working-directory: ./infra
        run: |
          npm install
          npm run build:all
      - name: Run tests
        working-directory: ./infra
        run: npm run test
      #############################
      # Deploy common environment #
      #############################
      - name: Check if feature branch exists in common-environment
        run: |
          branch_status_code=$(curl -I https://api.github.com/repos/almamedia/mepa-ovipro-common-environment/branches/${{ github.event.ref }} -H "Authorization: Bearer ${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}" | grep HTTP/ | awk {'print $2'})
          branch_exists=$(echo $(if [ "${branch_status_code}" = "200" ] ; then echo true; else echo false; fi))
          echo "common-env branch exists: ${branch_exists}, status code: ${branch_status_code}"
          echo "COMMON_ENVIRONMENT_FEATURE_BRANCH_ALREADY_EXISTS=${branch_exists}" >> $GITHUB_ENV
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        if: env.COMMON_ENVIRONMENT_FEATURE_BRANCH_ALREADY_EXISTS == 'false'
        name: Deploy common-environment
        with:
          owner: almamedia
          repo: mepa-ovipro-common-environment
          github_token: ${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}
          workflow_file_name: deploy-infra.yaml
          inputs: '{ "environment_name": "${{ github.event.ref }}" }'

      #######################
      # Deploy core backend #
      #######################
      - name: Check if feature branch in core-backend
        run: |
          branch_status_code=$(curl -I https://api.github.com/repos/almamedia/mepa-ovipro-core-backend/branches/${{ github.event.ref }} -H "Authorization: Bearer ${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}" | grep HTTP/ | awk {'print $2'})
          branch_exists=$(echo $(if [ "${branch_status_code}" = "200" ] ; then echo true; else echo false; fi))
          echo "core-backend branch exists: ${branch_exists}, status code: ${branch_status_code}"
          echo "CORE_BACKEND_DEPLOY_FEATURE_BRANCH_ALREADY_EXISTS=${branch_exists}" >> $GITHUB_ENV
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        if: env.CORE_BACKEND_DEPLOY_FEATURE_BRANCH_ALREADY_EXISTS == 'false'
        name: Deploy core-backend
        with:
          owner: almamedia
          repo: mepa-ovipro-core-backend
          github_token: ${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}
          workflow_file_name: deploy-infra.yaml
          inputs: '{ "environment_name": "${{ github.event.ref }}" }'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: eu-west-1
          role-to-assume: FIND_ME_AND_REPLACE_WITH_REPO_OIDC_ROLE_ARN
          role-session-name: full-deploy-feature-pipeline
      - name: deploy all stacks
        working-directory: ./infra
        run: |
          npx cdk deploy --context account=${{ env.ACCOUNT }} --context environment=${{ env.ENVIRONMENT }} --require-approval never --all
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.MEPA_ASUMINEN_OVIPRO_SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: 'ovi_pro_pipeline_development_deployments'
          status: STARTED
          color: good
      - name: Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.MEPA_ASUMINEN_OVIPRO_SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: 'ovi_pro_pipeline_development_deployments'
          status: FAILED
          color: danger
