name: OpenApi lint

on:
  push:
    branches: ["main"]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  # Any other API's are put as "job" to enable parallel prosessing
  api_name-v1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Open API Spectral Lint
      uses: stoplightio/spectral-action@v0.8.1
      with:
        file_glob: 'api-specs/*.{yaml,yml}'
