name: Production pipeline

on: 
  workflow_dispatch:
    inputs:
        version_tag:
          description: 'Version Tag'
          required: true
          default: '1.0.0'
    
jobs:
  Production_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version_tag }}      
      - name: set account to production & environment to production
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "ACCOUNT=prod" >> $GITHUB_ENV
      - name: configure AWS credentials for Code Artifact packages
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Get access for alma packages
        run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain almamedia --domain-owner 277005280161 --query authorizationToken --output text)" >> $GITHUB_ENV
      - name: install deps & build
        working-directory: ./infra
        run: |
          npm install --prefer-online
          npm run build:all
      - name: Run tests
        working-directory: ./infra
        run: npm run test
      - name: deploy all stacks
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CDK_PROD_USER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_PROD_USER_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile deploy_profile
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile deploy_profile
          aws configure set region eu-west-1 --profile deploy_profile
          npx cdk deploy --context account=${{ env.ACCOUNT }} --context environment=${{ env.ENVIRONMENT }} --profile deploy_profile --require-approval never --all

  Production_deploy:
    needs: [Production_infra]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.version_tag }}    
    - name: set account to production & environment to production
      run: |
        echo "ENVIRONMENT=production" >> $GITHUB_ENV
        echo "ACCOUNT=prod" >> $GITHUB_ENV
    - name: configure AWS credentials for Code Artifact packages
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Get access for alma packages
      run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain almamedia --domain-owner 277005280161 --query authorizationToken --output text)" >> $GITHUB_ENV
    - name: install deps & build
      working-directory: ./infra
      run: |
        npm install --prefer-online
        npm run build:all
    - name: deploy all stacks
      working-directory: ./infra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CDK_PROD_USER_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_PROD_USER_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile deploy_profile
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile deploy_profile
        aws configure set region eu-west-1 --profile deploy_profile
        npx cdk deploy --context account=${{ env.ACCOUNT }} --context environment=${{ env.ENVIRONMENT }} --profile deploy_profile --require-approval never --all
