name: Run tests

on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "infra/.nvmrc"
          cache: "npm"
          cache-dependency-path: "./infra/package-lock.json"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Get access for alma packages
        run: echo "GITHUB_ACCESS_TOKEN=${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}" >> $GITHUB_ENV
      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v2.3.0
        with:
          servers: |
            [{
                "id": "mepa-ovipro",
                "username": "${{ secrets.MEPA_GH_ACTIONS_BOT_USERNAME }}",
                "password": "${{ secrets.MEPA_GH_ACTIONS_BOT_TOKEN }}"
            }]
      - name: Install deps & build
        working-directory: ./infra
        run: |
          npm install --legacy-peer-deps
          npm run build:lambda:java
          npm run build:lambda:api-model
      - name: Run tests
        working-directory: ./infra
        run: npm run test:all
