on:
  schedule:
    # every day at 07:00
  - cron: 0 7 * * *
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Update dependencies manually'
name: Update node dependencies
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Configure AWS credentials for Code Artifact packages
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CODEARTIFACT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CODEARTIFACT_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Get access for alma packages
      run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain almamedia --domain-owner 277005280161 --query authorizationToken --output text)" >> $GITHUB_ENV
    - name: Update dependencies
      uses: neverendingqs/gh-action-node-update-deps@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        bump-version: patch
        package-manager: npm
        git-user-email: tata@eioleolemassa.aaa
        git-user-name: Depsubotti
        pre-commit-script: npm run build
        target: latest -x '/^(\@almamedia\/).*$/'
