name: OpenApi docs upload

on:
  push:
    paths:
      - 'api-docs/**'

jobs:
  upload-docs-to-s3:
    runs-on: ubuntu-latest
    ## run only on main branch
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    ## Create index page from html files in s3 bucket
    - name: Create index page & upload
      run: |
        chmod +x .github/workflows/scripts/create_docs_index_page.sh
        aws configure set aws_access_key_id ${{ secrets.MEPA_ASUMINEN_OVIPRO_DOCUMENTATION_DEPLOYMENT_ACCESS_KEY }} --profile deploy_profile
        aws configure set aws_secret_access_key ${{ secrets.MEPA_ASUMINEN_OVIPRO_DOCUMENTATION_DEPLOYMENT_SECRET_ACCESS_KEY }} --profile deploy_profile
        aws configure set region eu-west-1 --profile deploy_profile

        aws s3 cp api-docs s3://apidocs.dev-ovipro.net/ --region eu-west-1 --recursive --exclude "*" --include "*.html" --profile deploy_profile

        aws s3 ls apidocs.dev-ovipro.net --recursive --profile deploy_profile | awk '{if($4~/\.html$/){print $4}}' > files.txt

        .github/workflows/scripts/create_docs_index_page.sh files.txt > api-docs/index.html

        aws s3 cp api-docs s3://apidocs.dev-ovipro.net/ --region eu-west-1 --recursive --exclude "*" --include "index.html" --profile deploy_profile

